-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table tarea (
  id                            bigint generated by default as identity not null,
  completada                    boolean default false not null,
  nombre                        varchar(255),
  descripcion                   varchar(255),
  constraint pk_tarea primary key (id)
);


-- !Downs

-- drop all
drop table if exists tarea cascade;

